// Semitone Inc. Confidential Information.
// TM and (c) 2016-present Semitone Inc.  All Rights Reserved.
// Reproduction in whole or in part without prior written permission of a
// duly authorized representative is prohibited.

#pragma once

// System
#include <stdexcept>
#include <string>

namespace komp
{
#define KOMP_ENUM_CLASS_NAME SoundID

#define KOMP_ENUM_MEMBERS( KOMP_ENUM_VALUE ) \
KOMP_ENUM_VALUE( BRASS_ALPHORN, "brass.alphorn" ) \
KOMP_ENUM_VALUE( BRASS_ALTO_HORN, "brass.alto-horn" ) \
KOMP_ENUM_VALUE( BRASS_BARITONE_HORN, "brass.baritone-horn" ) \
KOMP_ENUM_VALUE( BRASS_BUGLE, "brass.bugle" ) \
KOMP_ENUM_VALUE( BRASS_BUGLE_ALTO, "brass.bugle.alto" ) \
KOMP_ENUM_VALUE( BRASS_BUGLE_BARITONE, "brass.bugle.baritone" ) \
KOMP_ENUM_VALUE( BRASS_BUGLE_CONTRABASS, "brass.bugle.contrabass" ) \
KOMP_ENUM_VALUE( BRASS_BUGLE_EUPHONIUM_BUGLE, "brass.bugle.euphonium-bugle" ) \
KOMP_ENUM_VALUE( BRASS_BUGLE_MELLOPHONE_BUGLE, "brass.bugle.mellophone-bugle" ) \
KOMP_ENUM_VALUE( BRASS_BUGLE_SOPRANO, "brass.bugle.soprano" ) \
KOMP_ENUM_VALUE( BRASS_CIMBASSO, "brass.cimbasso" ) \
KOMP_ENUM_VALUE( BRASS_CONCH_SHELL, "brass.conch-shell" ) \
KOMP_ENUM_VALUE( BRASS_CORNET, "brass.cornet" ) \
KOMP_ENUM_VALUE( BRASS_CORNET_SOPRANO, "brass.cornet.soprano" ) \
KOMP_ENUM_VALUE( BRASS_CORNETT, "brass.cornett" ) \
KOMP_ENUM_VALUE( BRASS_CORNETT_TENOR, "brass.cornett.tenor" ) \
KOMP_ENUM_VALUE( BRASS_CORNETTINO, "brass.cornettino" ) \
KOMP_ENUM_VALUE( BRASS_DIDGERIDOO, "brass.didgeridoo" ) \
KOMP_ENUM_VALUE( BRASS_EUPHONIUM, "brass.euphonium" ) \
KOMP_ENUM_VALUE( BRASS_FISCORN, "brass.fiscorn" ) \
KOMP_ENUM_VALUE( BRASS_FLUGELHORN, "brass.flugelhorn" ) \
KOMP_ENUM_VALUE( BRASS_FRENCH_HORN, "brass.french-horn" ) \
KOMP_ENUM_VALUE( BRASS_GROUP, "brass.group" ) \
KOMP_ENUM_VALUE( BRASS_GROUP_SYNTH, "brass.group.synth" ) \
KOMP_ENUM_VALUE( BRASS_HELICON, "brass.helicon" ) \
KOMP_ENUM_VALUE( BRASS_HORAGAI, "brass.horagai" ) \
KOMP_ENUM_VALUE( BRASS_KUHLOHORN, "brass.kuhlohorn" ) \
KOMP_ENUM_VALUE( BRASS_MELLOPHONE, "brass.mellophone" ) \
KOMP_ENUM_VALUE( BRASS_NATURAL_HORN, "brass.natural-horn" ) \
KOMP_ENUM_VALUE( BRASS_OPHICLEIDE, "brass.ophicleide" ) \
KOMP_ENUM_VALUE( BRASS_POSTHORN, "brass.posthorn" ) \
KOMP_ENUM_VALUE( BRASS_RAG_DUNG, "brass.rag-dung" ) \
KOMP_ENUM_VALUE( BRASS_SACKBUTT, "brass.sackbutt" ) \
KOMP_ENUM_VALUE( BRASS_SACKBUTT_ALTO, "brass.sackbutt.alto" ) \
KOMP_ENUM_VALUE( BRASS_SACKBUTT_BASS, "brass.sackbutt.bass" ) \
KOMP_ENUM_VALUE( BRASS_SACKBUTT_TENOR, "brass.sackbutt.tenor" ) \
KOMP_ENUM_VALUE( BRASS_SAXHORN, "brass.saxhorn" ) \
KOMP_ENUM_VALUE( BRASS_SERPENT, "brass.serpent" ) \
KOMP_ENUM_VALUE( BRASS_SHOFAR, "brass.shofar" ) \
KOMP_ENUM_VALUE( BRASS_SOUSAPHONE, "brass.sousaphone" ) \
KOMP_ENUM_VALUE( BRASS_TROMBONE, "brass.trombone" ) \
KOMP_ENUM_VALUE( BRASS_TROMBONE_ALTO, "brass.trombone.alto" ) \
KOMP_ENUM_VALUE( BRASS_TROMBONE_BASS, "brass.trombone.bass" ) \
KOMP_ENUM_VALUE( BRASS_TROMBONE_CONTRABASS, "brass.trombone.contrabass" ) \
KOMP_ENUM_VALUE( BRASS_TROMBONE_TENOR, "brass.trombone.tenor" ) \
KOMP_ENUM_VALUE( BRASS_TRUMPET, "brass.trumpet" ) \
KOMP_ENUM_VALUE( BRASS_TRUMPET_BAROQUE, "brass.trumpet.baroque" ) \
KOMP_ENUM_VALUE( BRASS_TRUMPET_BASS, "brass.trumpet.bass" ) \
KOMP_ENUM_VALUE( BRASS_TRUMPET_BFLAT, "brass.trumpet.bflat" ) \
KOMP_ENUM_VALUE( BRASS_TRUMPET_C, "brass.trumpet.c" ) \
KOMP_ENUM_VALUE( BRASS_TRUMPET_D, "brass.trumpet.d" ) \
KOMP_ENUM_VALUE( BRASS_TRUMPET_PICCOLO, "brass.trumpet.piccolo" ) \
KOMP_ENUM_VALUE( BRASS_TRUMPET_POCKET, "brass.trumpet.pocket" ) \
KOMP_ENUM_VALUE( BRASS_TRUMPET_SLIDE, "brass.trumpet.slide" ) \
KOMP_ENUM_VALUE( BRASS_TRUMPET_TENOR, "brass.trumpet.tenor" ) \
KOMP_ENUM_VALUE( BRASS_TUBA, "brass.tuba" ) \
KOMP_ENUM_VALUE( BRASS_TUBA_BASS, "brass.tuba.bass" ) \
KOMP_ENUM_VALUE( BRASS_TUBA_SUBCONTRABASS, "brass.tuba.subcontrabass" ) \
KOMP_ENUM_VALUE( BRASS_VIENNA_HORN, "brass.vienna-horn" ) \
KOMP_ENUM_VALUE( BRASS_VUVUZELA, "brass.vuvuzela" ) \
KOMP_ENUM_VALUE( BRASS_WAGNER_TUBA, "brass.wagner-tuba" ) \
KOMP_ENUM_VALUE( DRUM_APENTEMMA, "drum.apentemma" ) \
KOMP_ENUM_VALUE( DRUM_ASHIKO, "drum.ashiko" ) \
KOMP_ENUM_VALUE( DRUM_ATABAQUE, "drum.atabaque" ) \
KOMP_ENUM_VALUE( DRUM_ATOKE, "drum.atoke" ) \
KOMP_ENUM_VALUE( DRUM_ATSIMEVU, "drum.atsimevu" ) \
KOMP_ENUM_VALUE( DRUM_AXATSE, "drum.axatse" ) \
KOMP_ENUM_VALUE( DRUM_BASS_DRUM, "drum.bass-drum" ) \
KOMP_ENUM_VALUE( DRUM_BATA, "drum.bata" ) \
KOMP_ENUM_VALUE( DRUM_BATA_ITOTELE, "drum.bata.itotele" ) \
KOMP_ENUM_VALUE( DRUM_BATA_IYA, "drum.bata.iya" ) \
KOMP_ENUM_VALUE( DRUM_BATA_OKONKOLO, "drum.bata.okonkolo" ) \
KOMP_ENUM_VALUE( DRUM_BENDIR, "drum.bendir" ) \
KOMP_ENUM_VALUE( DRUM_BODHRAN, "drum.bodhran" ) \
KOMP_ENUM_VALUE( DRUM_BOMBO, "drum.bombo" ) \
KOMP_ENUM_VALUE( DRUM_BONGO, "drum.bongo" ) \
KOMP_ENUM_VALUE( DRUM_BOUGARABOU, "drum.bougarabou" ) \
KOMP_ENUM_VALUE( DRUM_BUFFALO_DRUM, "drum.buffalo-drum" ) \
KOMP_ENUM_VALUE( DRUM_CAJON, "drum.cajon" ) \
KOMP_ENUM_VALUE( DRUM_CHENDA, "drum.chenda" ) \
KOMP_ENUM_VALUE( DRUM_CHU_DAIKO, "drum.chu-daiko" ) \
KOMP_ENUM_VALUE( DRUM_CONGA, "drum.conga" ) \
KOMP_ENUM_VALUE( DRUM_CUICA, "drum.cuica" ) \
KOMP_ENUM_VALUE( DRUM_DABAKAN, "drum.dabakan" ) \
KOMP_ENUM_VALUE( DRUM_DAFF, "drum.daff" ) \
KOMP_ENUM_VALUE( DRUM_DAFLI, "drum.dafli" ) \
KOMP_ENUM_VALUE( DRUM_DAIBYOSI, "drum.daibyosi" ) \
KOMP_ENUM_VALUE( DRUM_DAMROO, "drum.damroo" ) \
KOMP_ENUM_VALUE( DRUM_DARABUKA, "drum.darabuka" ) \
KOMP_ENUM_VALUE( DRUM_DEF, "drum.def" ) \
KOMP_ENUM_VALUE( DRUM_DHOL, "drum.dhol" ) \
KOMP_ENUM_VALUE( DRUM_DHOLAK, "drum.dholak" ) \
KOMP_ENUM_VALUE( DRUM_DJEMBE, "drum.djembe" ) \
KOMP_ENUM_VALUE( DRUM_DOIRA, "drum.doira" ) \
KOMP_ENUM_VALUE( DRUM_DONDO, "drum.dondo" ) \
KOMP_ENUM_VALUE( DRUM_DOUN_DOUN_BA, "drum.doun-doun-ba" ) \
KOMP_ENUM_VALUE( DRUM_DUFF, "drum.duff" ) \
KOMP_ENUM_VALUE( DRUM_DUMBEK, "drum.dumbek" ) \
KOMP_ENUM_VALUE( DRUM_FONTOMFROM, "drum.fontomfrom" ) \
KOMP_ENUM_VALUE( DRUM_FRAME_DRUM, "drum.frame-drum" ) \
KOMP_ENUM_VALUE( DRUM_FRAME_DRUM_ARABIAN, "drum.frame-drum.arabian" ) \
KOMP_ENUM_VALUE( DRUM_GEDUK, "drum.geduk" ) \
KOMP_ENUM_VALUE( DRUM_GHATAM, "drum.ghatam" ) \
KOMP_ENUM_VALUE( DRUM_GOME, "drum.gome" ) \
KOMP_ENUM_VALUE( DRUM_GROUP, "drum.group" ) \
KOMP_ENUM_VALUE( DRUM_GROUP_CHINESE, "drum.group.chinese" ) \
KOMP_ENUM_VALUE( DRUM_GROUP_EWE, "drum.group.ewe" ) \
KOMP_ENUM_VALUE( DRUM_GROUP_INDIAN, "drum.group.indian" ) \
KOMP_ENUM_VALUE( DRUM_GROUP_SET, "drum.group.set" ) \
KOMP_ENUM_VALUE( DRUM_HAND_DRUM, "drum.hand-drum" ) \
KOMP_ENUM_VALUE( DRUM_HIRA_DAIKO, "drum.hira-daiko" ) \
KOMP_ENUM_VALUE( DRUM_IBO, "drum.ibo" ) \
KOMP_ENUM_VALUE( DRUM_IGIHUMURIZO, "drum.igihumurizo" ) \
KOMP_ENUM_VALUE( DRUM_INYAHURA, "drum.inyahura" ) \
KOMP_ENUM_VALUE( DRUM_ISHAKWE, "drum.ishakwe" ) \
KOMP_ENUM_VALUE( DRUM_JANG_GU, "drum.jang-gu" ) \
KOMP_ENUM_VALUE( DRUM_KAGAN, "drum.kagan" ) \
KOMP_ENUM_VALUE( DRUM_KAKKO, "drum.kakko" ) \
KOMP_ENUM_VALUE( DRUM_KANJIRA, "drum.kanjira" ) \
KOMP_ENUM_VALUE( DRUM_KENDHANG, "drum.kendhang" ) \
KOMP_ENUM_VALUE( DRUM_KENDHANG_AGENG, "drum.kendhang.ageng" ) \
KOMP_ENUM_VALUE( DRUM_KENDHANG_CIBLON, "drum.kendhang.ciblon" ) \
KOMP_ENUM_VALUE( DRUM_KENKENI, "drum.kenkeni" ) \
KOMP_ENUM_VALUE( DRUM_KHOL, "drum.khol" ) \
KOMP_ENUM_VALUE( DRUM_KICK_DRUM, "drum.kick-drum" ) \
KOMP_ENUM_VALUE( DRUM_KIDI, "drum.kidi" ) \
KOMP_ENUM_VALUE( DRUM_KO_DAIKO, "drum.ko-daiko" ) \
KOMP_ENUM_VALUE( DRUM_KPANLOGO, "drum.kpanlogo" ) \
KOMP_ENUM_VALUE( DRUM_KUDUM, "drum.kudum" ) \
KOMP_ENUM_VALUE( DRUM_LAMBEG, "drum.lambeg" ) \
KOMP_ENUM_VALUE( DRUM_LION_DRUM, "drum.lion-drum" ) \
KOMP_ENUM_VALUE( DRUM_LOG_DRUM, "drum.log-drum" ) \
KOMP_ENUM_VALUE( DRUM_LOG_DRUM_AFRICAN, "drum.log-drum.african" ) \
KOMP_ENUM_VALUE( DRUM_LOG_DRUM_NATIVE, "drum.log-drum.native" ) \
KOMP_ENUM_VALUE( DRUM_LOG_DRUM_NIGERIAN, "drum.log-drum.nigerian" ) \
KOMP_ENUM_VALUE( DRUM_MADAL, "drum.madal" ) \
KOMP_ENUM_VALUE( DRUM_MADDALE, "drum.maddale" ) \
KOMP_ENUM_VALUE( DRUM_MRIDANGAM, "drum.mridangam" ) \
KOMP_ENUM_VALUE( DRUM_NAAL, "drum.naal" ) \
KOMP_ENUM_VALUE( DRUM_NAGADO_DAIKO, "drum.nagado-daiko" ) \
KOMP_ENUM_VALUE( DRUM_NAGARA, "drum.nagara" ) \
KOMP_ENUM_VALUE( DRUM_NAQARA, "drum.naqara" ) \
KOMP_ENUM_VALUE( DRUM_O_DAIKO, "drum.o-daiko" ) \
KOMP_ENUM_VALUE( DRUM_OKAWA, "drum.okawa" ) \
KOMP_ENUM_VALUE( DRUM_OKEDO_DAIKO, "drum.okedo-daiko" ) \
KOMP_ENUM_VALUE( DRUM_PAHU_HULA, "drum.pahu-hula" ) \
KOMP_ENUM_VALUE( DRUM_PAKHAWAJ, "drum.pakhawaj" ) \
KOMP_ENUM_VALUE( DRUM_PANDEIRO, "drum.pandeiro" ) \
KOMP_ENUM_VALUE( DRUM_PANDERO, "drum.pandero" ) \
KOMP_ENUM_VALUE( DRUM_POWWOW, "drum.powwow" ) \
KOMP_ENUM_VALUE( DRUM_PUEBLO, "drum.pueblo" ) \
KOMP_ENUM_VALUE( DRUM_REPINIQUE, "drum.repinique" ) \
KOMP_ENUM_VALUE( DRUM_RIQ, "drum.riq" ) \
KOMP_ENUM_VALUE( DRUM_ROTOTOM, "drum.rototom" ) \
KOMP_ENUM_VALUE( DRUM_SABAR, "drum.sabar" ) \
KOMP_ENUM_VALUE( DRUM_SAKARA, "drum.sakara" ) \
KOMP_ENUM_VALUE( DRUM_SAMPHO, "drum.sampho" ) \
KOMP_ENUM_VALUE( DRUM_SANGBAN, "drum.sangban" ) \
KOMP_ENUM_VALUE( DRUM_SHIME_DAIKO, "drum.shime-daiko" ) \
KOMP_ENUM_VALUE( DRUM_SLIT_DRUM, "drum.slit-drum" ) \
KOMP_ENUM_VALUE( DRUM_SLIT_DRUM_KRIN, "drum.slit-drum.krin" ) \
KOMP_ENUM_VALUE( DRUM_SNARE_DRUM, "drum.snare-drum" ) \
KOMP_ENUM_VALUE( DRUM_SNARE_DRUM_ELECTRIC, "drum.snare-drum.electric" ) \
KOMP_ENUM_VALUE( DRUM_SOGO, "drum.sogo" ) \
KOMP_ENUM_VALUE( DRUM_SURDO, "drum.surdo" ) \
KOMP_ENUM_VALUE( DRUM_TABLA, "drum.tabla" ) \
KOMP_ENUM_VALUE( DRUM_TABLA_BAYAN, "drum.tabla.bayan" ) \
KOMP_ENUM_VALUE( DRUM_TABLA_DAYAN, "drum.tabla.dayan" ) \
KOMP_ENUM_VALUE( DRUM_TAIKO, "drum.taiko" ) \
KOMP_ENUM_VALUE( DRUM_TALKING, "drum.talking" ) \
KOMP_ENUM_VALUE( DRUM_TAMA, "drum.tama" ) \
KOMP_ENUM_VALUE( DRUM_TAMBORITA, "drum.tamborita" ) \
KOMP_ENUM_VALUE( DRUM_TAMBOURINE, "drum.tambourine" ) \
KOMP_ENUM_VALUE( DRUM_TAMTE, "drum.tamte" ) \
KOMP_ENUM_VALUE( DRUM_TANGKU, "drum.tangku" ) \
KOMP_ENUM_VALUE( DRUM_TAN_TAN, "drum.tan-tan" ) \
KOMP_ENUM_VALUE( DRUM_TAPHON, "drum.taphon" ) \
KOMP_ENUM_VALUE( DRUM_TAR, "drum.tar" ) \
KOMP_ENUM_VALUE( DRUM_TASHA, "drum.tasha" ) \
KOMP_ENUM_VALUE( DRUM_TENOR_DRUM, "drum.tenor-drum" ) \
KOMP_ENUM_VALUE( DRUM_TEPONAXTLI, "drum.teponaxtli" ) \
KOMP_ENUM_VALUE( DRUM_THAVIL, "drum.thavil" ) \
KOMP_ENUM_VALUE( DRUM_THE_BOX, "drum.the-box" ) \
KOMP_ENUM_VALUE( DRUM_TIMBALE, "drum.timbale" ) \
KOMP_ENUM_VALUE( DRUM_TIMPANI, "drum.timpani" ) \
KOMP_ENUM_VALUE( DRUM_TINAJA, "drum.tinaja" ) \
KOMP_ENUM_VALUE( DRUM_TOERE, "drum.toere" ) \
KOMP_ENUM_VALUE( DRUM_TOMBAK, "drum.tombak" ) \
KOMP_ENUM_VALUE( DRUM_TOM_TOM, "drum.tom-tom" ) \
KOMP_ENUM_VALUE( DRUM_TOM_TOM_SYNTH, "drum.tom-tom.synth" ) \
KOMP_ENUM_VALUE( DRUM_TSUZUMI, "drum.tsuzumi" ) \
KOMP_ENUM_VALUE( DRUM_TUMBAK, "drum.tumbak" ) \
KOMP_ENUM_VALUE( DRUM_UCHIWA_DAIKO, "drum.uchiwa-daiko" ) \
KOMP_ENUM_VALUE( DRUM_UDAKU, "drum.udaku" ) \
KOMP_ENUM_VALUE( DRUM_UDU, "drum.udu" ) \
KOMP_ENUM_VALUE( DRUM_ZARB, "drum.zarb" ) \
KOMP_ENUM_VALUE( EFFECT_AEOLIAN_HARP, "effect.aeolian-harp" ) \
KOMP_ENUM_VALUE( EFFECT_AIR_HORN, "effect.air-horn" ) \
KOMP_ENUM_VALUE( EFFECT_APPLAUSE, "effect.applause" ) \
KOMP_ENUM_VALUE( EFFECT_BASS_STRING_SLAP, "effect.bass-string-slap" ) \
KOMP_ENUM_VALUE( EFFECT_BIRD, "effect.bird" ) \
KOMP_ENUM_VALUE( EFFECT_BIRD_NIGHTINGALE, "effect.bird.nightingale" ) \
KOMP_ENUM_VALUE( EFFECT_BIRD_TWEET, "effect.bird.tweet" ) \
KOMP_ENUM_VALUE( EFFECT_BREATH, "effect.breath" ) \
KOMP_ENUM_VALUE( EFFECT_BUBBLE, "effect.bubble" ) \
KOMP_ENUM_VALUE( EFFECT_BULLROARER, "effect.bullroarer" ) \
KOMP_ENUM_VALUE( EFFECT_BURST, "effect.burst" ) \
KOMP_ENUM_VALUE( EFFECT_CAR, "effect.car" ) \
KOMP_ENUM_VALUE( EFFECT_CAR_CRASH, "effect.car.crash" ) \
KOMP_ENUM_VALUE( EFFECT_CAR_ENGINE, "effect.car.engine" ) \
KOMP_ENUM_VALUE( EFFECT_CAR_PASS, "effect.car.pass" ) \
KOMP_ENUM_VALUE( EFFECT_CAR_STOP, "effect.car.stop" ) \
KOMP_ENUM_VALUE( EFFECT_CRICKETS, "effect.crickets" ) \
KOMP_ENUM_VALUE( EFFECT_DOG, "effect.dog" ) \
KOMP_ENUM_VALUE( EFFECT_DOOR_CREAK, "effect.door.creak" ) \
KOMP_ENUM_VALUE( EFFECT_DOOR_SLAM, "effect.door.slam" ) \
KOMP_ENUM_VALUE( EFFECT_EXPLOSION, "effect.explosion" ) \
KOMP_ENUM_VALUE( EFFECT_FLUTE_KEY_CLICK, "effect.flute-key-click" ) \
KOMP_ENUM_VALUE( EFFECT_FOOTSTEPS, "effect.footsteps" ) \
KOMP_ENUM_VALUE( EFFECT_FROGS, "effect.frogs" ) \
KOMP_ENUM_VALUE( EFFECT_GUITAR_CUTTING, "effect.guitar-cutting" ) \
KOMP_ENUM_VALUE( EFFECT_GUITAR_FRET, "effect.guitar-fret" ) \
KOMP_ENUM_VALUE( EFFECT_GUNSHOT, "effect.gunshot" ) \
KOMP_ENUM_VALUE( EFFECT_HAND_CLAP, "effect.hand-clap" ) \
KOMP_ENUM_VALUE( EFFECT_HEARTBEAT, "effect.heartbeat" ) \
KOMP_ENUM_VALUE( EFFECT_HELICOPTER, "effect.helicopter" ) \
KOMP_ENUM_VALUE( EFFECT_HIGH_Q, "effect.high-q" ) \
KOMP_ENUM_VALUE( EFFECT_HORSE_GALLOP, "effect.horse-gallop" ) \
KOMP_ENUM_VALUE( EFFECT_JET_PLANE, "effect.jet-plane" ) \
KOMP_ENUM_VALUE( EFFECT_LASER_GUN, "effect.laser-gun" ) \
KOMP_ENUM_VALUE( EFFECT_LAUGH, "effect.laugh" ) \
KOMP_ENUM_VALUE( EFFECT_LIONS_ROAR, "effect.lions-roar" ) \
KOMP_ENUM_VALUE( EFFECT_MACHINE_GUN, "effect.machine-gun" ) \
KOMP_ENUM_VALUE( EFFECT_MARCHING_MACHINE, "effect.marching-machine" ) \
KOMP_ENUM_VALUE( EFFECT_METRONOME_BELL, "effect.metronome-bell" ) \
KOMP_ENUM_VALUE( EFFECT_METRONOME_CLICK, "effect.metronome-click" ) \
KOMP_ENUM_VALUE( EFFECT_PAT, "effect.pat" ) \
KOMP_ENUM_VALUE( EFFECT_PUNCH, "effect.punch" ) \
KOMP_ENUM_VALUE( EFFECT_RAIN, "effect.rain" ) \
KOMP_ENUM_VALUE( EFFECT_SCRATCH, "effect.scratch" ) \
KOMP_ENUM_VALUE( EFFECT_SCREAM, "effect.scream" ) \
KOMP_ENUM_VALUE( EFFECT_SEASHORE, "effect.seashore" ) \
KOMP_ENUM_VALUE( EFFECT_SIREN, "effect.siren" ) \
KOMP_ENUM_VALUE( EFFECT_SLAP, "effect.slap" ) \
KOMP_ENUM_VALUE( EFFECT_SNAP, "effect.snap" ) \
KOMP_ENUM_VALUE( EFFECT_STAMP, "effect.stamp" ) \
KOMP_ENUM_VALUE( EFFECT_STARSHIP, "effect.starship" ) \
KOMP_ENUM_VALUE( EFFECT_STREAM, "effect.stream" ) \
KOMP_ENUM_VALUE( EFFECT_TELEPHONE_RING, "effect.telephone-ring" ) \
KOMP_ENUM_VALUE( EFFECT_THUNDER, "effect.thunder" ) \
KOMP_ENUM_VALUE( EFFECT_TRAIN, "effect.train" ) \
KOMP_ENUM_VALUE( EFFECT_TRASH_CAN, "effect.trash-can" ) \
KOMP_ENUM_VALUE( EFFECT_WHIP, "effect.whip" ) \
KOMP_ENUM_VALUE( EFFECT_WHISTLE, "effect.whistle" ) \
KOMP_ENUM_VALUE( EFFECT_WHISTLE_MOUTH_SIREN, "effect.whistle.mouth-siren" ) \
KOMP_ENUM_VALUE( EFFECT_WHISTLE_POLICE, "effect.whistle.police" ) \
KOMP_ENUM_VALUE( EFFECT_WHISTLE_SLIDE, "effect.whistle.slide" ) \
KOMP_ENUM_VALUE( EFFECT_WHISTLE_TRAIN, "effect.whistle.train" ) \
KOMP_ENUM_VALUE( EFFECT_WIND, "effect.wind" ) \
KOMP_ENUM_VALUE( KEYBOARD_ACCORDION, "keyboard.accordion" ) \
KOMP_ENUM_VALUE( KEYBOARD_BANDONEON, "keyboard.bandoneon" ) \
KOMP_ENUM_VALUE( KEYBOARD_CELESTA, "keyboard.celesta" ) \
KOMP_ENUM_VALUE( KEYBOARD_CLAVICHORD, "keyboard.clavichord" ) \
KOMP_ENUM_VALUE( KEYBOARD_CLAVICHORD_SYNTH, "keyboard.clavichord.synth" ) \
KOMP_ENUM_VALUE( KEYBOARD_CONCERTINA, "keyboard.concertina" ) \
KOMP_ENUM_VALUE( KEYBOARD_FORTEPIANO, "keyboard.fortepiano" ) \
KOMP_ENUM_VALUE( KEYBOARD_HARMONIUM, "keyboard.harmonium" ) \
KOMP_ENUM_VALUE( KEYBOARD_HARPSICHORD, "keyboard.harpsichord" ) \
KOMP_ENUM_VALUE( KEYBOARD_ONDES_MARTENOT, "keyboard.ondes-martenot" ) \
KOMP_ENUM_VALUE( KEYBOARD_ORGAN, "keyboard.organ" ) \
KOMP_ENUM_VALUE( KEYBOARD_ORGAN_DRAWBAR, "keyboard.organ.drawbar" ) \
KOMP_ENUM_VALUE( KEYBOARD_ORGAN_PERCUSSIVE, "keyboard.organ.percussive" ) \
KOMP_ENUM_VALUE( KEYBOARD_ORGAN_PIPE, "keyboard.organ.pipe" ) \
KOMP_ENUM_VALUE( KEYBOARD_ORGAN_REED, "keyboard.organ.reed" ) \
KOMP_ENUM_VALUE( KEYBOARD_ORGAN_ROTARY, "keyboard.organ.rotary" ) \
KOMP_ENUM_VALUE( KEYBOARD_PIANO, "keyboard.piano" ) \
KOMP_ENUM_VALUE( KEYBOARD_PIANO_ELECTRIC, "keyboard.piano.electric" ) \
KOMP_ENUM_VALUE( KEYBOARD_PIANO_GRAND, "keyboard.piano.grand" ) \
KOMP_ENUM_VALUE( KEYBOARD_PIANO_HONKY_TONK, "keyboard.piano.honky-tonk" ) \
KOMP_ENUM_VALUE( KEYBOARD_PIANO_PREPARED, "keyboard.piano.prepared" ) \
KOMP_ENUM_VALUE( KEYBOARD_PIANO_TOY, "keyboard.piano.toy" ) \
KOMP_ENUM_VALUE( KEYBOARD_PIANO_UPRIGHT, "keyboard.piano.upright" ) \
KOMP_ENUM_VALUE( KEYBOARD_VIRGINAL, "keyboard.virginal" ) \
KOMP_ENUM_VALUE( METAL_ADODO, "metal.adodo" ) \
KOMP_ENUM_VALUE( METAL_ANVIL, "metal.anvil" ) \
KOMP_ENUM_VALUE( METAL_BABENDIL, "metal.babendil" ) \
KOMP_ENUM_VALUE( METAL_BELLS_AGOGO, "metal.bells.agogo" ) \
KOMP_ENUM_VALUE( METAL_BELLS_ALMGLOCKEN, "metal.bells.almglocken" ) \
KOMP_ENUM_VALUE( METAL_BELLS_BELL_PLATE, "metal.bells.bell-plate" ) \
KOMP_ENUM_VALUE( METAL_BELLS_BELL_TREE, "metal.bells.bell-tree" ) \
KOMP_ENUM_VALUE( METAL_BELLS_CARILLON, "metal.bells.carillon" ) \
KOMP_ENUM_VALUE( METAL_BELLS_CHIMES, "metal.bells.chimes" ) \
KOMP_ENUM_VALUE( METAL_BELLS_CHIMTA, "metal.bells.chimta" ) \
KOMP_ENUM_VALUE( METAL_BELLS_CHIPPLI, "metal.bells.chippli" ) \
KOMP_ENUM_VALUE( METAL_BELLS_CHURCH, "metal.bells.church" ) \
KOMP_ENUM_VALUE( METAL_BELLS_COWBELL, "metal.bells.cowbell" ) \
KOMP_ENUM_VALUE( METAL_BELLS_DAWURO, "metal.bells.dawuro" ) \
KOMP_ENUM_VALUE( METAL_BELLS_GANKOKWE, "metal.bells.gankokwe" ) \
KOMP_ENUM_VALUE( METAL_BELLS_GHUNGROO, "metal.bells.ghungroo" ) \
KOMP_ENUM_VALUE( METAL_BELLS_HATHELI, "metal.bells.hatheli" ) \
KOMP_ENUM_VALUE( METAL_BELLS_JINGLE_BELL, "metal.bells.jingle-bell" ) \
KOMP_ENUM_VALUE( METAL_BELLS_KHARTAL, "metal.bells.khartal" ) \
KOMP_ENUM_VALUE( METAL_BELLS_MARK_TREE, "metal.bells.mark-tree" ) \
KOMP_ENUM_VALUE( METAL_BELLS_SISTRUM, "metal.bells.sistrum" ) \
KOMP_ENUM_VALUE( METAL_BELLS_SLEIGH_BELLS, "metal.bells.sleigh-bells" ) \
KOMP_ENUM_VALUE( METAL_BELLS_TEMPLE, "metal.bells.temple" ) \
KOMP_ENUM_VALUE( METAL_BELLS_TIBETAN, "metal.bells.tibetan" ) \
KOMP_ENUM_VALUE( METAL_BELLS_TINKLEBELL, "metal.bells.tinklebell" ) \
KOMP_ENUM_VALUE( METAL_BELLS_TRYCHEL, "metal.bells.trychel" ) \
KOMP_ENUM_VALUE( METAL_BELLS_WIND_CHIMES, "metal.bells.wind-chimes" ) \
KOMP_ENUM_VALUE( METAL_BELLS_ZILLS, "metal.bells.zills" ) \
KOMP_ENUM_VALUE( METAL_BERIMBAU, "metal.berimbau" ) \
KOMP_ENUM_VALUE( METAL_BRAKE_DRUMS, "metal.brake-drums" ) \
KOMP_ENUM_VALUE( METAL_CROTALES, "metal.crotales" ) \
KOMP_ENUM_VALUE( METAL_CYMBAL_BO, "metal.cymbal.bo" ) \
KOMP_ENUM_VALUE( METAL_CYMBAL_CENG_CENG, "metal.cymbal.ceng-ceng" ) \
KOMP_ENUM_VALUE( METAL_CYMBAL_CHABARA, "metal.cymbal.chabara" ) \
KOMP_ENUM_VALUE( METAL_CYMBAL_CHINESE, "metal.cymbal.chinese" ) \
KOMP_ENUM_VALUE( METAL_CYMBAL_CHING, "metal.cymbal.ching" ) \
KOMP_ENUM_VALUE( METAL_CYMBAL_CLASH, "metal.cymbal.clash" ) \
KOMP_ENUM_VALUE( METAL_CYMBAL_CRASH, "metal.cymbal.crash" ) \
KOMP_ENUM_VALUE( METAL_CYMBAL_FINGER, "metal.cymbal.finger" ) \
KOMP_ENUM_VALUE( METAL_CYMBAL_HAND, "metal.cymbal.hand" ) \
KOMP_ENUM_VALUE( METAL_CYMBAL_KESI, "metal.cymbal.kesi" ) \
KOMP_ENUM_VALUE( METAL_CYMBAL_MANJEERA, "metal.cymbal.manjeera" ) \
KOMP_ENUM_VALUE( METAL_CYMBAL_REVERSE, "metal.cymbal.reverse" ) \
KOMP_ENUM_VALUE( METAL_CYMBAL_RIDE, "metal.cymbal.ride" ) \
KOMP_ENUM_VALUE( METAL_CYMBAL_SIZZLE, "metal.cymbal.sizzle" ) \
KOMP_ENUM_VALUE( METAL_CYMBAL_SPLASH, "metal.cymbal.splash" ) \
KOMP_ENUM_VALUE( METAL_CYMBAL_SUSPENDED, "metal.cymbal.suspended" ) \
KOMP_ENUM_VALUE( METAL_CYMBAL_TEBYOSHI, "metal.cymbal.tebyoshi" ) \
KOMP_ENUM_VALUE( METAL_CYMBAL_TIBETAN, "metal.cymbal.tibetan" ) \
KOMP_ENUM_VALUE( METAL_CYMBAL_TINGSHA, "metal.cymbal.tingsha" ) \
KOMP_ENUM_VALUE( METAL_FLEXATONE, "metal.flexatone" ) \
KOMP_ENUM_VALUE( METAL_GONG, "metal.gong" ) \
KOMP_ENUM_VALUE( METAL_GONG_AGENG, "metal.gong.ageng" ) \
KOMP_ENUM_VALUE( METAL_GONG_AGUNG, "metal.gong.agung" ) \
KOMP_ENUM_VALUE( METAL_GONG_CHANCHIKI, "metal.gong.chanchiki" ) \
KOMP_ENUM_VALUE( METAL_GONG_CHINESE, "metal.gong.chinese" ) \
KOMP_ENUM_VALUE( METAL_GONG_GANDINGAN, "metal.gong.gandingan" ) \
KOMP_ENUM_VALUE( METAL_GONG_KEMPUL, "metal.gong.kempul" ) \
KOMP_ENUM_VALUE( METAL_GONG_KEMPYANG, "metal.gong.kempyang" ) \
KOMP_ENUM_VALUE( METAL_GONG_KETUK, "metal.gong.ketuk" ) \
KOMP_ENUM_VALUE( METAL_GONG_KKWENGGWARI, "metal.gong.kkwenggwari" ) \
KOMP_ENUM_VALUE( METAL_GONG_LUO, "metal.gong.luo" ) \
KOMP_ENUM_VALUE( METAL_GONG_SINGING, "metal.gong.singing" ) \
KOMP_ENUM_VALUE( METAL_GONG_THAI, "metal.gong.thai" ) \
KOMP_ENUM_VALUE( METAL_GUIRA, "metal.guira" ) \
KOMP_ENUM_VALUE( METAL_HANG, "metal.hang" ) \
KOMP_ENUM_VALUE( METAL_HI_HAT, "metal.hi-hat" ) \
KOMP_ENUM_VALUE( METAL_JAW_HARP, "metal.jaw-harp" ) \
KOMP_ENUM_VALUE( METAL_KENGONG, "metal.kengong" ) \
KOMP_ENUM_VALUE( METAL_MURCHANG, "metal.murchang" ) \
KOMP_ENUM_VALUE( METAL_MUSICAL_SAW, "metal.musical-saw" ) \
KOMP_ENUM_VALUE( METAL_SINGING_BOWL, "metal.singing-bowl" ) \
KOMP_ENUM_VALUE( METAL_SPOONS, "metal.spoons" ) \
KOMP_ENUM_VALUE( METAL_STEEL_DRUMS, "metal.steel-drums" ) \
KOMP_ENUM_VALUE( METAL_TAMTAM, "metal.tamtam" ) \
KOMP_ENUM_VALUE( METAL_THUNDERSHEET, "metal.thundersheet" ) \
KOMP_ENUM_VALUE( METAL_TRIANGLE, "metal.triangle" ) \
KOMP_ENUM_VALUE( METAL_WASHBOARD, "metal.washboard" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_ANGKLUNG, "pitched-percussion.angklung" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_BALAFON, "pitched-percussion.balafon" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_BELL_LYRE, "pitched-percussion.bell-lyre" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_BELLS, "pitched-percussion.bells" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_BIANQING, "pitched-percussion.bianqing" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_BIANZHONG, "pitched-percussion.bianzhong" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_BONANG, "pitched-percussion.bonang" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_CIMBALOM, "pitched-percussion.cimbalom" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_CRYSTAL_GLASSES, "pitched-percussion.crystal-glasses" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_DAN_TAM_THAP_LUC, "pitched-percussion.dan-tam-thap-luc" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_FANGXIANG, "pitched-percussion.fangxiang" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_GANDINGAN_A_KAYO, "pitched-percussion.gandingan-a-kayo" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_GANGSA, "pitched-percussion.gangsa" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_GENDER, "pitched-percussion.gender" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_GIYING, "pitched-percussion.giying" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_GLASS_HARMONICA, "pitched-percussion.glass-harmonica" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_GLOCKENSPIEL, "pitched-percussion.glockenspiel" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_GLOCKENSPIEL_ALTO, "pitched-percussion.glockenspiel.alto" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_GLOCKENSPIEL_SOPRANO, "pitched-percussion.glockenspiel.soprano" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_GYIL, "pitched-percussion.gyil" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_HAMMER_DULCIMER, "pitched-percussion.hammer-dulcimer" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_HANDBELLS, "pitched-percussion.handbells" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_KALIMBA, "pitched-percussion.kalimba" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_KANTIL, "pitched-percussion.kantil" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_KHIM, "pitched-percussion.khim" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_KULINTANG, "pitched-percussion.kulintang" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_KULINTANG_A_KAYO, "pitched-percussion.kulintang-a-kayo" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_KULINTANG_A_TINIOK, "pitched-percussion.kulintang-a-tiniok" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_LIKEMBE, "pitched-percussion.likembe" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_LUNTANG, "pitched-percussion.luntang" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_MARIMBA, "pitched-percussion.marimba" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_MARIMBA_BASS, "pitched-percussion.marimba.bass" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_MBIRA, "pitched-percussion.mbira" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_MBIRA_ARRAY, "pitched-percussion.mbira.array" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_METALLOPHONE, "pitched-percussion.metallophone" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_METALLOPHONE_ALTO, "pitched-percussion.metallophone.alto" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_METALLOPHONE_BASS, "pitched-percussion.metallophone.bass" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_METALLOPHONE_SOPRANO, "pitched-percussion.metallophone.soprano" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_MUSIC_BOX, "pitched-percussion.music-box" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_PELOG_PANERUS, "pitched-percussion.pelog-panerus" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_PEMADE, "pitched-percussion.pemade" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_PENYACAH, "pitched-percussion.penyacah" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_RANAT_EK, "pitched-percussion.ranat.ek" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_RANAT_EK_LEK, "pitched-percussion.ranat.ek-lek" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_RANAT_THUM, "pitched-percussion.ranat.thum" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_RANAT_THUM_LEK, "pitched-percussion.ranat.thum-lek" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_REYONG, "pitched-percussion.reyong" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_SANZA, "pitched-percussion.sanza" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_SARON_BARUNG, "pitched-percussion.saron-barung" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_SARON_DEMONG, "pitched-percussion.saron-demong" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_SARON_PANERUS, "pitched-percussion.saron-panerus" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_SLENDRO_PANERUS, "pitched-percussion.slendro-panerus" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_SLENTEM, "pitched-percussion.slentem" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_TSYMBALY, "pitched-percussion.tsymbaly" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_TUBES, "pitched-percussion.tubes" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_TUBULAR_BELLS, "pitched-percussion.tubular-bells" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_VIBRAPHONE, "pitched-percussion.vibraphone" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_XYLOPHONE, "pitched-percussion.xylophone" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_XYLOPHONE_ALTO, "pitched-percussion.xylophone.alto" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_XYLOPHONE_BASS, "pitched-percussion.xylophone.bass" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_XYLOPHONE_SOPRANO, "pitched-percussion.xylophone.soprano" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_XYLORIMBA, "pitched-percussion.xylorimba" ) \
KOMP_ENUM_VALUE( PITCHED_PERCUSSION_YANGQIN, "pitched-percussion.yangqin" ) \
KOMP_ENUM_VALUE( PLUCK_ARCHLUTE, "pluck.archlute" ) \
KOMP_ENUM_VALUE( PLUCK_AUTOHARP, "pluck.autoharp" ) \
KOMP_ENUM_VALUE( PLUCK_BAGLAMA, "pluck.baglama" ) \
KOMP_ENUM_VALUE( PLUCK_BAJO, "pluck.bajo" ) \
KOMP_ENUM_VALUE( PLUCK_BALALAIKA, "pluck.balalaika" ) \
KOMP_ENUM_VALUE( PLUCK_BALALAIKA_ALTO, "pluck.balalaika.alto" ) \
KOMP_ENUM_VALUE( PLUCK_BALALAIKA_BASS, "pluck.balalaika.bass" ) \
KOMP_ENUM_VALUE( PLUCK_BALALAIKA_CONTRABASS, "pluck.balalaika.contrabass" ) \
KOMP_ENUM_VALUE( PLUCK_BALALAIKA_PICCOLO, "pluck.balalaika.piccolo" ) \
KOMP_ENUM_VALUE( PLUCK_BALALAIKA_PRIMA, "pluck.balalaika.prima" ) \
KOMP_ENUM_VALUE( PLUCK_BALALAIKA_SECUNDA, "pluck.balalaika.secunda" ) \
KOMP_ENUM_VALUE( PLUCK_BANDOLA, "pluck.bandola" ) \
KOMP_ENUM_VALUE( PLUCK_BANDURA, "pluck.bandura" ) \
KOMP_ENUM_VALUE( PLUCK_BANDURRIA, "pluck.bandurria" ) \
KOMP_ENUM_VALUE( PLUCK_BANJO, "pluck.banjo" ) \
KOMP_ENUM_VALUE( PLUCK_BANJO_TENOR, "pluck.banjo.tenor" ) \
KOMP_ENUM_VALUE( PLUCK_BANJOLELE, "pluck.banjolele" ) \
KOMP_ENUM_VALUE( PLUCK_BARBAT, "pluck.barbat" ) \
KOMP_ENUM_VALUE( PLUCK_BASS, "pluck.bass" ) \
KOMP_ENUM_VALUE( PLUCK_BASS_ACOUSTIC, "pluck.bass.acoustic" ) \
KOMP_ENUM_VALUE( PLUCK_BASS_BOLON, "pluck.bass.bolon" ) \
KOMP_ENUM_VALUE( PLUCK_BASS_ELECTRIC, "pluck.bass.electric" ) \
KOMP_ENUM_VALUE( PLUCK_BASS_FRETLESS, "pluck.bass.fretless" ) \
KOMP_ENUM_VALUE( PLUCK_BASS_GUITARRON, "pluck.bass.guitarron" ) \
KOMP_ENUM_VALUE( PLUCK_BASS_SYNTH, "pluck.bass.synth" ) \
KOMP_ENUM_VALUE( PLUCK_BASS_SYNTH_LEAD, "pluck.bass.synth.lead" ) \
KOMP_ENUM_VALUE( PLUCK_BASS_WASHTUB, "pluck.bass.washtub" ) \
KOMP_ENUM_VALUE( PLUCK_BASS_WHAMOLA, "pluck.bass.whamola" ) \
KOMP_ENUM_VALUE( PLUCK_BEGENA, "pluck.begena" ) \
KOMP_ENUM_VALUE( PLUCK_BIWA, "pluck.biwa" ) \
KOMP_ENUM_VALUE( PLUCK_BORDONUA, "pluck.bordonua" ) \
KOMP_ENUM_VALUE( PLUCK_BOUZOUKI, "pluck.bouzouki" ) \
KOMP_ENUM_VALUE( PLUCK_BOUZOUKI_IRISH, "pluck.bouzouki.irish" ) \
KOMP_ENUM_VALUE( PLUCK_CELTIC_HARP, "pluck.celtic-harp" ) \
KOMP_ENUM_VALUE( PLUCK_CHARANGO, "pluck.charango" ) \
KOMP_ENUM_VALUE( PLUCK_CHITARRA_BATTENTE, "pluck.chitarra-battente" ) \
KOMP_ENUM_VALUE( PLUCK_CITHARA, "pluck.cithara" ) \
KOMP_ENUM_VALUE( PLUCK_CITTERN, "pluck.cittern" ) \
KOMP_ENUM_VALUE( PLUCK_CUATRO, "pluck.cuatro" ) \
KOMP_ENUM_VALUE( PLUCK_DAN_BAU, "pluck.dan-bau" ) \
KOMP_ENUM_VALUE( PLUCK_DAN_NGUYET, "pluck.dan-nguyet" ) \
KOMP_ENUM_VALUE( PLUCK_DAN_TRANH, "pluck.dan-tranh" ) \
KOMP_ENUM_VALUE( PLUCK_DAN_TY_BA, "pluck.dan-ty-ba" ) \
KOMP_ENUM_VALUE( PLUCK_DIDDLEY_BOW, "pluck.diddley-bow" ) \
KOMP_ENUM_VALUE( PLUCK_DOMRA, "pluck.domra" ) \
KOMP_ENUM_VALUE( PLUCK_DOMU, "pluck.domu" ) \
KOMP_ENUM_VALUE( PLUCK_DULCIMER, "pluck.dulcimer" ) \
KOMP_ENUM_VALUE( PLUCK_DUTAR, "pluck.dutar" ) \
KOMP_ENUM_VALUE( PLUCK_DUXIANQIN, "pluck.duxianqin" ) \
KOMP_ENUM_VALUE( PLUCK_EKTARA, "pluck.ektara" ) \
KOMP_ENUM_VALUE( PLUCK_GEOMUNGO, "pluck.geomungo" ) \
KOMP_ENUM_VALUE( PLUCK_GOTTUVADHYAM, "pluck.gottuvadhyam" ) \
KOMP_ENUM_VALUE( PLUCK_GUITAR, "pluck.guitar" ) \
KOMP_ENUM_VALUE( PLUCK_GUITAR_ACOUSTIC, "pluck.guitar.acoustic" ) \
KOMP_ENUM_VALUE( PLUCK_GUITAR_ELECTRIC, "pluck.guitar.electric" ) \
KOMP_ENUM_VALUE( PLUCK_GUITAR_NYLON_STRING, "pluck.guitar.nylon-string" ) \
KOMP_ENUM_VALUE( PLUCK_GUITAR_PEDAL_STEEL, "pluck.guitar.pedal-steel" ) \
KOMP_ENUM_VALUE( PLUCK_GUITAR_PORTUGUESE, "pluck.guitar.portuguese" ) \
KOMP_ENUM_VALUE( PLUCK_GUITAR_REQUINTO, "pluck.guitar.requinto" ) \
KOMP_ENUM_VALUE( PLUCK_GUITAR_RESONATOR, "pluck.guitar.resonator" ) \
KOMP_ENUM_VALUE( PLUCK_GUITAR_STEEL_STRING, "pluck.guitar.steel-string" ) \
KOMP_ENUM_VALUE( PLUCK_GUITJO, "pluck.guitjo" ) \
KOMP_ENUM_VALUE( PLUCK_GUITJO_DOUBLE_NECK, "pluck.guitjo.double-neck" ) \
KOMP_ENUM_VALUE( PLUCK_GUQIN, "pluck.guqin" ) \
KOMP_ENUM_VALUE( PLUCK_GUZHENG, "pluck.guzheng" ) \
KOMP_ENUM_VALUE( PLUCK_GUZHENG_CHOAZHOU, "pluck.guzheng.choazhou" ) \
KOMP_ENUM_VALUE( PLUCK_HARP, "pluck.harp" ) \
KOMP_ENUM_VALUE( PLUCK_HARP_GUITAR, "pluck.harp-guitar" ) \
KOMP_ENUM_VALUE( PLUCK_HUAPANGUERA, "pluck.huapanguera" ) \
KOMP_ENUM_VALUE( PLUCK_JARANA_HUASTECA, "pluck.jarana-huasteca" ) \
KOMP_ENUM_VALUE( PLUCK_JARANA_JAROCHA, "pluck.jarana-jarocha" ) \
KOMP_ENUM_VALUE( PLUCK_JARANA_JAROCHA_MOSQUITO, "pluck.jarana-jarocha.mosquito" ) \
KOMP_ENUM_VALUE( PLUCK_JARANA_JAROCHA_PRIMERA, "pluck.jarana-jarocha.primera" ) \
KOMP_ENUM_VALUE( PLUCK_JARANA_JAROCHA_SEGUNDA, "pluck.jarana-jarocha.segunda" ) \
KOMP_ENUM_VALUE( PLUCK_JARANA_JAROCHA_TERCERA, "pluck.jarana-jarocha.tercera" ) \
KOMP_ENUM_VALUE( PLUCK_KABOSY, "pluck.kabosy" ) \
KOMP_ENUM_VALUE( PLUCK_KANTELE, "pluck.kantele" ) \
KOMP_ENUM_VALUE( PLUCK_KANUN, "pluck.kanun" ) \
KOMP_ENUM_VALUE( PLUCK_KAYAGUM, "pluck.kayagum" ) \
KOMP_ENUM_VALUE( PLUCK_KOBZA, "pluck.kobza" ) \
KOMP_ENUM_VALUE( PLUCK_KOMUZ, "pluck.komuz" ) \
KOMP_ENUM_VALUE( PLUCK_KORA, "pluck.kora" ) \
KOMP_ENUM_VALUE( PLUCK_KOTO, "pluck.koto" ) \
KOMP_ENUM_VALUE( PLUCK_KUTIYAPI, "pluck.kutiyapi" ) \
KOMP_ENUM_VALUE( PLUCK_LANGELEIK, "pluck.langeleik" ) \
KOMP_ENUM_VALUE( PLUCK_LAUD, "pluck.laud" ) \
KOMP_ENUM_VALUE( PLUCK_LUTE, "pluck.lute" ) \
KOMP_ENUM_VALUE( PLUCK_LYRE, "pluck.lyre" ) \
KOMP_ENUM_VALUE( PLUCK_MANDOBASS, "pluck.mandobass" ) \
KOMP_ENUM_VALUE( PLUCK_MANDOCELLO, "pluck.mandocello" ) \
KOMP_ENUM_VALUE( PLUCK_MANDOLA, "pluck.mandola" ) \
KOMP_ENUM_VALUE( PLUCK_MANDOLIN, "pluck.mandolin" ) \
KOMP_ENUM_VALUE( PLUCK_MANDOLIN_OCTAVE, "pluck.mandolin.octave" ) \
KOMP_ENUM_VALUE( PLUCK_MANDORA, "pluck.mandora" ) \
KOMP_ENUM_VALUE( PLUCK_MANDORE, "pluck.mandore" ) \
KOMP_ENUM_VALUE( PLUCK_MAROVANY, "pluck.marovany" ) \
KOMP_ENUM_VALUE( PLUCK_MUSICAL_BOW, "pluck.musical-bow" ) \
KOMP_ENUM_VALUE( PLUCK_NGONI, "pluck.ngoni" ) \
KOMP_ENUM_VALUE( PLUCK_OUD, "pluck.oud" ) \
KOMP_ENUM_VALUE( PLUCK_PIPA, "pluck.pipa" ) \
KOMP_ENUM_VALUE( PLUCK_PSALTERY, "pluck.psaltery" ) \
KOMP_ENUM_VALUE( PLUCK_RUAN, "pluck.ruan" ) \
KOMP_ENUM_VALUE( PLUCK_SALLANEH, "pluck.sallaneh" ) \
KOMP_ENUM_VALUE( PLUCK_SANSHIN, "pluck.sanshin" ) \
KOMP_ENUM_VALUE( PLUCK_SANTOOR, "pluck.santoor" ) \
KOMP_ENUM_VALUE( PLUCK_SANXIAN, "pluck.sanxian" ) \
KOMP_ENUM_VALUE( PLUCK_SAROD, "pluck.sarod" ) \
KOMP_ENUM_VALUE( PLUCK_SAUNG, "pluck.saung" ) \
KOMP_ENUM_VALUE( PLUCK_SAZ, "pluck.saz" ) \
KOMP_ENUM_VALUE( PLUCK_SE, "pluck.se" ) \
KOMP_ENUM_VALUE( PLUCK_SETAR, "pluck.setar" ) \
KOMP_ENUM_VALUE( PLUCK_SHAMISEN, "pluck.shamisen" ) \
KOMP_ENUM_VALUE( PLUCK_SITAR, "pluck.sitar" ) \
KOMP_ENUM_VALUE( PLUCK_SYNTH, "pluck.synth" ) \
KOMP_ENUM_VALUE( PLUCK_SYNTH_CHARANG, "pluck.synth.charang" ) \
KOMP_ENUM_VALUE( PLUCK_SYNTH_CHIFF, "pluck.synth.chiff" ) \
KOMP_ENUM_VALUE( PLUCK_SYNTH_STICK, "pluck.synth.stick" ) \
KOMP_ENUM_VALUE( PLUCK_TAMBURA, "pluck.tambura" ) \
KOMP_ENUM_VALUE( PLUCK_TAMBURA_BULGARIAN, "pluck.tambura.bulgarian" ) \
KOMP_ENUM_VALUE( PLUCK_TAMBURA_FEMALE, "pluck.tambura.female" ) \
KOMP_ENUM_VALUE( PLUCK_TAMBURA_MALE, "pluck.tambura.male" ) \
KOMP_ENUM_VALUE( PLUCK_TAR, "pluck.tar" ) \
KOMP_ENUM_VALUE( PLUCK_THEORBO, "pluck.theorbo" ) \
KOMP_ENUM_VALUE( PLUCK_TIMPLE, "pluck.timple" ) \
KOMP_ENUM_VALUE( PLUCK_TIPLE, "pluck.tiple" ) \
KOMP_ENUM_VALUE( PLUCK_TRES, "pluck.tres" ) \
KOMP_ENUM_VALUE( PLUCK_UKULELE, "pluck.ukulele" ) \
KOMP_ENUM_VALUE( PLUCK_UKULELE_TENOR, "pluck.ukulele.tenor" ) \
KOMP_ENUM_VALUE( PLUCK_VALIHA, "pluck.valiha" ) \
KOMP_ENUM_VALUE( PLUCK_VEENA, "pluck.veena" ) \
KOMP_ENUM_VALUE( PLUCK_VEENA_MOHAN, "pluck.veena.mohan" ) \
KOMP_ENUM_VALUE( PLUCK_VEENA_RUDRA, "pluck.veena.rudra" ) \
KOMP_ENUM_VALUE( PLUCK_VEENA_VICHITRA, "pluck.veena.vichitra" ) \
KOMP_ENUM_VALUE( PLUCK_VIHUELA, "pluck.vihuela" ) \
KOMP_ENUM_VALUE( PLUCK_VIHUELA_MEXICAN, "pluck.vihuela.mexican" ) \
KOMP_ENUM_VALUE( PLUCK_XALAM, "pluck.xalam" ) \
KOMP_ENUM_VALUE( PLUCK_YUEQIN, "pluck.yueqin" ) \
KOMP_ENUM_VALUE( PLUCK_ZITHER, "pluck.zither" ) \
KOMP_ENUM_VALUE( PLUCK_ZITHER_OVERTONE, "pluck.zither.overtone" ) \
KOMP_ENUM_VALUE( RATTLE_AFOXE, "rattle.afoxe" ) \
KOMP_ENUM_VALUE( RATTLE_BIRDS, "rattle.birds" ) \
KOMP_ENUM_VALUE( RATTLE_CABASA, "rattle.cabasa" ) \
KOMP_ENUM_VALUE( RATTLE_CAXIXI, "rattle.caxixi" ) \
KOMP_ENUM_VALUE( RATTLE_COG, "rattle.cog" ) \
KOMP_ENUM_VALUE( RATTLE_GANZA, "rattle.ganza" ) \
KOMP_ENUM_VALUE( RATTLE_HOSHO, "rattle.hosho" ) \
KOMP_ENUM_VALUE( RATTLE_JAWBONE, "rattle.jawbone" ) \
KOMP_ENUM_VALUE( RATTLE_KAYAMBA, "rattle.kayamba" ) \
KOMP_ENUM_VALUE( RATTLE_KPOKO_KPOKO, "rattle.kpoko-kpoko" ) \
KOMP_ENUM_VALUE( RATTLE_LAVA_STONES, "rattle.lava-stones" ) \
KOMP_ENUM_VALUE( RATTLE_MARACA, "rattle.maraca" ) \
KOMP_ENUM_VALUE( RATTLE_RAIN_STICK, "rattle.rain-stick" ) \
KOMP_ENUM_VALUE( RATTLE_RATCHET, "rattle.ratchet" ) \
KOMP_ENUM_VALUE( RATTLE_RATTLE, "rattle.rattle" ) \
KOMP_ENUM_VALUE( RATTLE_SHAKER, "rattle.shaker" ) \
KOMP_ENUM_VALUE( RATTLE_SHAKER_EGG, "rattle.shaker.egg" ) \
KOMP_ENUM_VALUE( RATTLE_SHEKERE, "rattle.shekere" ) \
KOMP_ENUM_VALUE( RATTLE_SISTRE, "rattle.sistre" ) \
KOMP_ENUM_VALUE( RATTLE_TELEVI, "rattle.televi" ) \
KOMP_ENUM_VALUE( RATTLE_VIBRASLAP, "rattle.vibraslap" ) \
KOMP_ENUM_VALUE( RATTLE_WASEMBE, "rattle.wasembe" ) \
KOMP_ENUM_VALUE( STRINGS_AJAENG, "strings.ajaeng" ) \
KOMP_ENUM_VALUE( STRINGS_ARPEGGIONE, "strings.arpeggione" ) \
KOMP_ENUM_VALUE( STRINGS_BARYTON, "strings.baryton" ) \
KOMP_ENUM_VALUE( STRINGS_CELLO, "strings.cello" ) \
KOMP_ENUM_VALUE( STRINGS_CELLO_PICCOLO, "strings.cello.piccolo" ) \
KOMP_ENUM_VALUE( STRINGS_CONTRABASS, "strings.contrabass" ) \
KOMP_ENUM_VALUE( STRINGS_CRWTH, "strings.crwth" ) \
KOMP_ENUM_VALUE( STRINGS_DAN_GAO, "strings.dan-gao" ) \
KOMP_ENUM_VALUE( STRINGS_DIHU, "strings.dihu" ) \
KOMP_ENUM_VALUE( STRINGS_ERHU, "strings.erhu" ) \
KOMP_ENUM_VALUE( STRINGS_ERXIAN, "strings.erxian" ) \
KOMP_ENUM_VALUE( STRINGS_ESRAJ, "strings.esraj" ) \
KOMP_ENUM_VALUE( STRINGS_FIDDLE, "strings.fiddle" ) \
KOMP_ENUM_VALUE( STRINGS_FIDDLE_HARDANGER, "strings.fiddle.hardanger" ) \
KOMP_ENUM_VALUE( STRINGS_GADULKA, "strings.gadulka" ) \
KOMP_ENUM_VALUE( STRINGS_GAOHU, "strings.gaohu" ) \
KOMP_ENUM_VALUE( STRINGS_GEHU, "strings.gehu" ) \
KOMP_ENUM_VALUE( STRINGS_GROUP, "strings.group" ) \
KOMP_ENUM_VALUE( STRINGS_GROUP_SYNTH, "strings.group.synth" ) \
KOMP_ENUM_VALUE( STRINGS_HAEGEUM, "strings.haegeum" ) \
KOMP_ENUM_VALUE( STRINGS_HURDY_GURDY, "strings.hurdy-gurdy" ) \
KOMP_ENUM_VALUE( STRINGS_IGIL, "strings.igil" ) \
KOMP_ENUM_VALUE( STRINGS_KAMANCHA, "strings.kamancha" ) \
KOMP_ENUM_VALUE( STRINGS_KOKYU, "strings.kokyu" ) \
KOMP_ENUM_VALUE( STRINGS_LARUAN, "strings.laruan" ) \
KOMP_ENUM_VALUE( STRINGS_LEIQIN, "strings.leiqin" ) \
KOMP_ENUM_VALUE( STRINGS_LIRONE, "strings.lirone" ) \
KOMP_ENUM_VALUE( STRINGS_LYRA_BYZANTINE, "strings.lyra.byzantine" ) \
KOMP_ENUM_VALUE( STRINGS_LYRA_CRETAN, "strings.lyra.cretan" ) \
KOMP_ENUM_VALUE( STRINGS_MORIN_KHUUR, "strings.morin-khuur" ) \
KOMP_ENUM_VALUE( STRINGS_NYCKELHARPA, "strings.nyckelharpa" ) \
KOMP_ENUM_VALUE( STRINGS_OCTOBASS, "strings.octobass" ) \
KOMP_ENUM_VALUE( STRINGS_REBAB, "strings.rebab" ) \
KOMP_ENUM_VALUE( STRINGS_REBEC, "strings.rebec" ) \
KOMP_ENUM_VALUE( STRINGS_SARANGI, "strings.sarangi" ) \
KOMP_ENUM_VALUE( STRINGS_STROH_VIOLIN, "strings.stroh-violin" ) \
KOMP_ENUM_VALUE( STRINGS_TROMBA_MARINA, "strings.tromba-marina" ) \
KOMP_ENUM_VALUE( STRINGS_VIELLE, "strings.vielle" ) \
KOMP_ENUM_VALUE( STRINGS_VIOL, "strings.viol" ) \
KOMP_ENUM_VALUE( STRINGS_VIOL_ALTO, "strings.viol.alto" ) \
KOMP_ENUM_VALUE( STRINGS_VIOL_BASS, "strings.viol.bass" ) \
KOMP_ENUM_VALUE( STRINGS_VIOL_TENOR, "strings.viol.tenor" ) \
KOMP_ENUM_VALUE( STRINGS_VIOL_TREBLE, "strings.viol.treble" ) \
KOMP_ENUM_VALUE( STRINGS_VIOL_VIOLONE, "strings.viol.violone" ) \
KOMP_ENUM_VALUE( STRINGS_VIOLA, "strings.viola" ) \
KOMP_ENUM_VALUE( STRINGS_VIOLA_DAMORE, "strings.viola-damore" ) \
KOMP_ENUM_VALUE( STRINGS_VIOLIN, "strings.violin" ) \
KOMP_ENUM_VALUE( STRINGS_VIOLONO_PICCOLO, "strings.violono.piccolo" ) \
KOMP_ENUM_VALUE( STRINGS_VIOLOTTA, "strings.violotta" ) \
KOMP_ENUM_VALUE( STRINGS_YAYLI_TANBUR, "strings.yayli-tanbur" ) \
KOMP_ENUM_VALUE( STRINGS_YAZHENG, "strings.yazheng" ) \
KOMP_ENUM_VALUE( STRINGS_ZHONGHU, "strings.zhonghu" ) \
KOMP_ENUM_VALUE( SYNTH_EFFECTS, "synth.effects" ) \
KOMP_ENUM_VALUE( SYNTH_EFFECTS_ATMOSPHERE, "synth.effects.atmosphere" ) \
KOMP_ENUM_VALUE( SYNTH_EFFECTS_BRIGHTNESS, "synth.effects.brightness" ) \
KOMP_ENUM_VALUE( SYNTH_EFFECTS_CRYSTAL, "synth.effects.crystal" ) \
KOMP_ENUM_VALUE( SYNTH_EFFECTS_ECHOES, "synth.effects.echoes" ) \
KOMP_ENUM_VALUE( SYNTH_EFFECTS_GOBLINS, "synth.effects.goblins" ) \
KOMP_ENUM_VALUE( SYNTH_EFFECTS_RAIN, "synth.effects.rain" ) \
KOMP_ENUM_VALUE( SYNTH_EFFECTS_SCI_FI, "synth.effects.sci-fi" ) \
KOMP_ENUM_VALUE( SYNTH_EFFECTS_SOUNDTRACK, "synth.effects.soundtrack" ) \
KOMP_ENUM_VALUE( SYNTH_GROUP, "synth.group" ) \
KOMP_ENUM_VALUE( SYNTH_GROUP_FIFTHS, "synth.group.fifths" ) \
KOMP_ENUM_VALUE( SYNTH_GROUP_ORCHESTRA, "synth.group.orchestra" ) \
KOMP_ENUM_VALUE( SYNTH_PAD, "synth.pad" ) \
KOMP_ENUM_VALUE( SYNTH_PAD_BOWED, "synth.pad.bowed" ) \
KOMP_ENUM_VALUE( SYNTH_PAD_CHOIR, "synth.pad.choir" ) \
KOMP_ENUM_VALUE( SYNTH_PAD_HALO, "synth.pad.halo" ) \
KOMP_ENUM_VALUE( SYNTH_PAD_METALLIC, "synth.pad.metallic" ) \
KOMP_ENUM_VALUE( SYNTH_PAD_POLYSYNTH, "synth.pad.polysynth" ) \
KOMP_ENUM_VALUE( SYNTH_PAD_SWEEP, "synth.pad.sweep" ) \
KOMP_ENUM_VALUE( SYNTH_PAD_WARM, "synth.pad.warm" ) \
KOMP_ENUM_VALUE( SYNTH_THEREMIN, "synth.theremin" ) \
KOMP_ENUM_VALUE( SYNTH_TONE_SAWTOOTH, "synth.tone.sawtooth" ) \
KOMP_ENUM_VALUE( SYNTH_TONE_SINE, "synth.tone.sine" ) \
KOMP_ENUM_VALUE( SYNTH_TONE_SQUARE, "synth.tone.square" ) \
KOMP_ENUM_VALUE( VOICE_AA, "voice.aa" ) \
KOMP_ENUM_VALUE( VOICE_ALTO, "voice.alto" ) \
KOMP_ENUM_VALUE( VOICE_AW, "voice.aw" ) \
KOMP_ENUM_VALUE( VOICE_BARITONE, "voice.baritone" ) \
KOMP_ENUM_VALUE( VOICE_BASS, "voice.bass" ) \
KOMP_ENUM_VALUE( VOICE_CHILD, "voice.child" ) \
KOMP_ENUM_VALUE( VOICE_COUNTERTENOR, "voice.countertenor" ) \
KOMP_ENUM_VALUE( VOICE_DOO, "voice.doo" ) \
KOMP_ENUM_VALUE( VOICE_EE, "voice.ee" ) \
KOMP_ENUM_VALUE( VOICE_FEMALE, "voice.female" ) \
KOMP_ENUM_VALUE( VOICE_KAZOO, "voice.kazoo" ) \
KOMP_ENUM_VALUE( VOICE_MALE, "voice.male" ) \
KOMP_ENUM_VALUE( VOICE_MEZZO_SOPRANO, "voice.mezzo-soprano" ) \
KOMP_ENUM_VALUE( VOICE_MM, "voice.mm" ) \
KOMP_ENUM_VALUE( VOICE_OO, "voice.oo" ) \
KOMP_ENUM_VALUE( VOICE_PERCUSSION, "voice.percussion" ) \
KOMP_ENUM_VALUE( VOICE_PERCUSSION_BEATBOX, "voice.percussion.beatbox" ) \
KOMP_ENUM_VALUE( VOICE_SOPRANO, "voice.soprano" ) \
KOMP_ENUM_VALUE( VOICE_SYNTH, "voice.synth" ) \
KOMP_ENUM_VALUE( VOICE_TALK_BOX, "voice.talk-box" ) \
KOMP_ENUM_VALUE( VOICE_TENOR, "voice.tenor" ) \
KOMP_ENUM_VALUE( VOICE_VOCALS, "voice.vocals" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_BANSURI, "wind.flutes.bansuri" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_BLOWN_BOTTLE, "wind.flutes.blown-bottle" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_CALLIOPE, "wind.flutes.calliope" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_DANSO, "wind.flutes.danso" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_DI_ZI, "wind.flutes.di-zi" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_DVOJNICE, "wind.flutes.dvojnice" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_FIFE, "wind.flutes.fife" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_FLAGEOLET, "wind.flutes.flageolet" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_FLUTE, "wind.flutes.flute" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_FLUTE_ALTO, "wind.flutes.flute.alto" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_FLUTE_BASS, "wind.flutes.flute.bass" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_FLUTE_CONTRA_ALTO, "wind.flutes.flute.contra-alto" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_FLUTE_CONTRABASS, "wind.flutes.flute.contrabass" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_FLUTE_DOUBLE_CONTRABASS, "wind.flutes.flute.double-contrabass" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_FLUTE_IRISH, "wind.flutes.flute.irish" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_FLUTE_PICCOLO, "wind.flutes.flute.piccolo" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_FLUTE_SUBCONTRABASS, "wind.flutes.flute.subcontrabass" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_FUJARA, "wind.flutes.fujara" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_GEMSHORN, "wind.flutes.gemshorn" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_HOCCHIKU, "wind.flutes.hocchiku" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_HUN, "wind.flutes.hun" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_KAVAL, "wind.flutes.kaval" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_KAWALA, "wind.flutes.kawala" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_KHLUI, "wind.flutes.khlui" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_KNOTWEED, "wind.flutes.knotweed" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_KONCOVKA_ALTO, "wind.flutes.koncovka.alto" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_KOUDI, "wind.flutes.koudi" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_NEY, "wind.flutes.ney" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_NOHKAN, "wind.flutes.nohkan" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_NOSE, "wind.flutes.nose" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_OCARINA, "wind.flutes.ocarina" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_OVERTONE_TENOR, "wind.flutes.overtone.tenor" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_PALENDAG, "wind.flutes.palendag" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_PANPIPES, "wind.flutes.panpipes" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_QUENA, "wind.flutes.quena" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_RECORDER, "wind.flutes.recorder" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_RECORDER_ALTO, "wind.flutes.recorder.alto" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_RECORDER_BASS, "wind.flutes.recorder.bass" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_RECORDER_CONTRABASS, "wind.flutes.recorder.contrabass" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_RECORDER_DESCANT, "wind.flutes.recorder.descant" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_RECORDER_GARKLEIN, "wind.flutes.recorder.garklein" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_RECORDER_GREAT_BASS, "wind.flutes.recorder.great-bass" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_RECORDER_SOPRANINO, "wind.flutes.recorder.sopranino" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_RECORDER_SOPRANO, "wind.flutes.recorder.soprano" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_RECORDER_TENOR, "wind.flutes.recorder.tenor" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_RYUTEKI, "wind.flutes.ryuteki" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_SHAKUHACHI, "wind.flutes.shakuhachi" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_SHEPHERDS_PIPE, "wind.flutes.shepherds-pipe" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_SHINOBUE, "wind.flutes.shinobue" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_SHVI, "wind.flutes.shvi" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_SULING, "wind.flutes.suling" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_TARKA, "wind.flutes.tarka" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_TUMPONG, "wind.flutes.tumpong" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_VENU, "wind.flutes.venu" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_WHISTLE, "wind.flutes.whistle" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_WHISTLE_ALTO, "wind.flutes.whistle.alto" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_WHISTLE_LOW_IRISH, "wind.flutes.whistle.low-irish" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_WHISTLE_SHIVA, "wind.flutes.whistle.shiva" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_WHISTLE_SLIDE, "wind.flutes.whistle.slide" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_WHISTLE_TIN, "wind.flutes.whistle.tin" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_WHISTLE_TIN_BFLAT, "wind.flutes.whistle.tin.bflat" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_WHISTLE_TIN_D, "wind.flutes.whistle.tin.d" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_XIAO, "wind.flutes.xiao" ) \
KOMP_ENUM_VALUE( WIND_FLUTES_XUN, "wind.flutes.xun" ) \
KOMP_ENUM_VALUE( WIND_GROUP, "wind.group" ) \
KOMP_ENUM_VALUE( WIND_JUG, "wind.jug" ) \
KOMP_ENUM_VALUE( WIND_PIPES_BAGPIPES, "wind.pipes.bagpipes" ) \
KOMP_ENUM_VALUE( WIND_PIPES_GAIDA, "wind.pipes.gaida" ) \
KOMP_ENUM_VALUE( WIND_PIPES_HIGHLAND, "wind.pipes.highland" ) \
KOMP_ENUM_VALUE( WIND_PIPES_UILLEANN, "wind.pipes.uilleann" ) \
KOMP_ENUM_VALUE( WIND_PUNGI, "wind.pungi" ) \
KOMP_ENUM_VALUE( WIND_REED_ALBOGUE, "wind.reed.albogue" ) \
KOMP_ENUM_VALUE( WIND_REED_ALBOKA, "wind.reed.alboka" ) \
KOMP_ENUM_VALUE( WIND_REED_ALGAITA, "wind.reed.algaita" ) \
KOMP_ENUM_VALUE( WIND_REED_ARGHUL, "wind.reed.arghul" ) \
KOMP_ENUM_VALUE( WIND_REED_BASSET_HORN, "wind.reed.basset-horn" ) \
KOMP_ENUM_VALUE( WIND_REED_BASSOON, "wind.reed.bassoon" ) \
KOMP_ENUM_VALUE( WIND_REED_BAWU, "wind.reed.bawu" ) \
KOMP_ENUM_VALUE( WIND_REED_BIFORA, "wind.reed.bifora" ) \
KOMP_ENUM_VALUE( WIND_REED_BOMBARDE, "wind.reed.bombarde" ) \
KOMP_ENUM_VALUE( WIND_REED_CHALUMEAU, "wind.reed.chalumeau" ) \
KOMP_ENUM_VALUE( WIND_REED_CLARINET, "wind.reed.clarinet" ) \
KOMP_ENUM_VALUE( WIND_REED_CLARINET_A, "wind.reed.clarinet.a" ) \
KOMP_ENUM_VALUE( WIND_REED_CLARINET_ALTO, "wind.reed.clarinet.alto" ) \
KOMP_ENUM_VALUE( WIND_REED_CLARINET_BASS, "wind.reed.clarinet.bass" ) \
KOMP_ENUM_VALUE( WIND_REED_CLARINET_BASSET, "wind.reed.clarinet.basset" ) \
KOMP_ENUM_VALUE( WIND_REED_CLARINET_BFLAT, "wind.reed.clarinet.bflat" ) \
KOMP_ENUM_VALUE( WIND_REED_CLARINET_CONTRA_ALTO, "wind.reed.clarinet.contra-alto" ) \
KOMP_ENUM_VALUE( WIND_REED_CLARINET_CONTRABASS, "wind.reed.clarinet.contrabass" ) \
KOMP_ENUM_VALUE( WIND_REED_CLARINET_EFLAT, "wind.reed.clarinet.eflat" ) \
KOMP_ENUM_VALUE( WIND_REED_CLARINET_PICCOLO_AFLAT, "wind.reed.clarinet.piccolo.aflat" ) \
KOMP_ENUM_VALUE( WIND_REED_CLARINETTE_DAMOUR, "wind.reed.clarinette-damour" ) \
KOMP_ENUM_VALUE( WIND_REED_CONTRABASS, "wind.reed.contrabass" ) \
KOMP_ENUM_VALUE( WIND_REED_CONTRABASSOON, "wind.reed.contrabassoon" ) \
KOMP_ENUM_VALUE( WIND_REED_CORNAMUSE, "wind.reed.cornamuse" ) \
KOMP_ENUM_VALUE( WIND_REED_CROMORNE, "wind.reed.cromorne" ) \
KOMP_ENUM_VALUE( WIND_REED_CRUMHORN, "wind.reed.crumhorn" ) \
KOMP_ENUM_VALUE( WIND_REED_CRUMHORN_ALTO, "wind.reed.crumhorn.alto" ) \
KOMP_ENUM_VALUE( WIND_REED_CRUMHORN_BASS, "wind.reed.crumhorn.bass" ) \
KOMP_ENUM_VALUE( WIND_REED_CRUMHORN_GREAT_BASS, "wind.reed.crumhorn.great-bass" ) \
KOMP_ENUM_VALUE( WIND_REED_CRUMHORN_SOPRANO, "wind.reed.crumhorn.soprano" ) \
KOMP_ENUM_VALUE( WIND_REED_CRUMHORN_TENOR, "wind.reed.crumhorn.tenor" ) \
KOMP_ENUM_VALUE( WIND_REED_DIPLE, "wind.reed.diple" ) \
KOMP_ENUM_VALUE( WIND_REED_DIPLICA, "wind.reed.diplica" ) \
KOMP_ENUM_VALUE( WIND_REED_DUDUK, "wind.reed.duduk" ) \
KOMP_ENUM_VALUE( WIND_REED_DULCIAN, "wind.reed.dulcian" ) \
KOMP_ENUM_VALUE( WIND_REED_DULZAINA, "wind.reed.dulzaina" ) \
KOMP_ENUM_VALUE( WIND_REED_ENGLISH_HORN, "wind.reed.english-horn" ) \
KOMP_ENUM_VALUE( WIND_REED_GUANZI, "wind.reed.guanzi" ) \
KOMP_ENUM_VALUE( WIND_REED_HARMONICA, "wind.reed.harmonica" ) \
KOMP_ENUM_VALUE( WIND_REED_HARMONICA_BASS, "wind.reed.harmonica.bass" ) \
KOMP_ENUM_VALUE( WIND_REED_HECKEL_CLARINA, "wind.reed.heckel-clarina" ) \
KOMP_ENUM_VALUE( WIND_REED_HECKELPHONE, "wind.reed.heckelphone" ) \
KOMP_ENUM_VALUE( WIND_REED_HECKELPHONE_PICCOLO, "wind.reed.heckelphone.piccolo" ) \
KOMP_ENUM_VALUE( WIND_REED_HECKELPHONE_CLARINET, "wind.reed.heckelphone-clarinet" ) \
KOMP_ENUM_VALUE( WIND_REED_HICHIRIKI, "wind.reed.hichiriki" ) \
KOMP_ENUM_VALUE( WIND_REED_HIRTENSCHALMEI, "wind.reed.hirtenschalmei" ) \
KOMP_ENUM_VALUE( WIND_REED_HNE, "wind.reed.hne" ) \
KOMP_ENUM_VALUE( WIND_REED_HORNPIPE, "wind.reed.hornpipe" ) \
KOMP_ENUM_VALUE( WIND_REED_HOUGUAN, "wind.reed.houguan" ) \
KOMP_ENUM_VALUE( WIND_REED_HULUSI, "wind.reed.hulusi" ) \
KOMP_ENUM_VALUE( WIND_REED_JOGI_BAJA, "wind.reed.jogi-baja" ) \
KOMP_ENUM_VALUE( WIND_REED_KEN_BAU, "wind.reed.ken-bau" ) \
KOMP_ENUM_VALUE( WIND_REED_KHAEN_MOUTH_ORGAN, "wind.reed.khaen-mouth-organ" ) \
KOMP_ENUM_VALUE( WIND_REED_LAUNEDDAS, "wind.reed.launeddas" ) \
KOMP_ENUM_VALUE( WIND_REED_MAQRUNAH, "wind.reed.maqrunah" ) \
KOMP_ENUM_VALUE( WIND_REED_MELODICA, "wind.reed.melodica" ) \
KOMP_ENUM_VALUE( WIND_REED_MIJWIZ, "wind.reed.mijwiz" ) \
KOMP_ENUM_VALUE( WIND_REED_MIZMAR, "wind.reed.mizmar" ) \
KOMP_ENUM_VALUE( WIND_REED_NADASWARAM, "wind.reed.nadaswaram" ) \
KOMP_ENUM_VALUE( WIND_REED_OBOE, "wind.reed.oboe" ) \
KOMP_ENUM_VALUE( WIND_REED_OBOE_BASS, "wind.reed.oboe.bass" ) \
KOMP_ENUM_VALUE( WIND_REED_OBOE_PICCOLO, "wind.reed.oboe.piccolo" ) \
KOMP_ENUM_VALUE( WIND_REED_OBOE_DA_CACCIA, "wind.reed.oboe-da-caccia" ) \
KOMP_ENUM_VALUE( WIND_REED_OBOE_DAMORE, "wind.reed.oboe-damore" ) \
KOMP_ENUM_VALUE( WIND_REED_OCTAVIN, "wind.reed.octavin" ) \
KOMP_ENUM_VALUE( WIND_REED_PI, "wind.reed.pi" ) \
KOMP_ENUM_VALUE( WIND_REED_PIBGORN, "wind.reed.pibgorn" ) \
KOMP_ENUM_VALUE( WIND_REED_PIRI, "wind.reed.piri" ) \
KOMP_ENUM_VALUE( WIND_REED_RACKETT, "wind.reed.rackett" ) \
KOMP_ENUM_VALUE( WIND_REED_RAUSCHPFEIFE, "wind.reed.rauschpfeife" ) \
KOMP_ENUM_VALUE( WIND_REED_RHAITA, "wind.reed.rhaita" ) \
KOMP_ENUM_VALUE( WIND_REED_ROTHPHONE, "wind.reed.rothphone" ) \
KOMP_ENUM_VALUE( WIND_REED_SARRUSAPHONE, "wind.reed.sarrusaphone" ) \
KOMP_ENUM_VALUE( WIND_REED_SAXONETTE, "wind.reed.saxonette" ) \
KOMP_ENUM_VALUE( WIND_REED_SAXOPHONE, "wind.reed.saxophone" ) \
KOMP_ENUM_VALUE( WIND_REED_SAXOPHONE_ALTO, "wind.reed.saxophone.alto" ) \
KOMP_ENUM_VALUE( WIND_REED_SAXOPHONE_AULOCHROME, "wind.reed.saxophone.aulochrome" ) \
KOMP_ENUM_VALUE( WIND_REED_SAXOPHONE_BARITONE, "wind.reed.saxophone.baritone" ) \
KOMP_ENUM_VALUE( WIND_REED_SAXOPHONE_BASS, "wind.reed.saxophone.bass" ) \
KOMP_ENUM_VALUE( WIND_REED_SAXOPHONE_CONTRABASS, "wind.reed.saxophone.contrabass" ) \
KOMP_ENUM_VALUE( WIND_REED_SAXOPHONE_MELODY, "wind.reed.saxophone.melody" ) \
KOMP_ENUM_VALUE( WIND_REED_SAXOPHONE_MEZZO_SOPRANO, "wind.reed.saxophone.mezzo-soprano" ) \
KOMP_ENUM_VALUE( WIND_REED_SAXOPHONE_SOPRANINO, "wind.reed.saxophone.sopranino" ) \
KOMP_ENUM_VALUE( WIND_REED_SAXOPHONE_SOPRANISSIMO, "wind.reed.saxophone.sopranissimo" ) \
KOMP_ENUM_VALUE( WIND_REED_SAXOPHONE_SOPRANO, "wind.reed.saxophone.soprano" ) \
KOMP_ENUM_VALUE( WIND_REED_SAXOPHONE_SUBCONTRABASS, "wind.reed.saxophone.subcontrabass" ) \
KOMP_ENUM_VALUE( WIND_REED_SAXOPHONE_TENOR, "wind.reed.saxophone.tenor" ) \
KOMP_ENUM_VALUE( WIND_REED_SHAWM, "wind.reed.shawm" ) \
KOMP_ENUM_VALUE( WIND_REED_SHENAI, "wind.reed.shenai" ) \
KOMP_ENUM_VALUE( WIND_REED_SHENG, "wind.reed.sheng" ) \
KOMP_ENUM_VALUE( WIND_REED_SIPSI, "wind.reed.sipsi" ) \
KOMP_ENUM_VALUE( WIND_REED_SOPILA, "wind.reed.sopila" ) \
KOMP_ENUM_VALUE( WIND_REED_SORNA, "wind.reed.sorna" ) \
KOMP_ENUM_VALUE( WIND_REED_SRALAI, "wind.reed.sralai" ) \
KOMP_ENUM_VALUE( WIND_REED_SUONA, "wind.reed.suona" ) \
KOMP_ENUM_VALUE( WIND_REED_SURNAI, "wind.reed.surnai" ) \
KOMP_ENUM_VALUE( WIND_REED_TAEPYEONGSO, "wind.reed.taepyeongso" ) \
KOMP_ENUM_VALUE( WIND_REED_TAROGATO, "wind.reed.tarogato" ) \
KOMP_ENUM_VALUE( WIND_REED_TAROGATO_ANCIENT, "wind.reed.tarogato.ancient" ) \
KOMP_ENUM_VALUE( WIND_REED_TROMPETA_CHINA, "wind.reed.trompeta-china" ) \
KOMP_ENUM_VALUE( WIND_REED_TUBAX, "wind.reed.tubax" ) \
KOMP_ENUM_VALUE( WIND_REED_XAPHOON, "wind.reed.xaphoon" ) \
KOMP_ENUM_VALUE( WIND_REED_ZHALEIKA, "wind.reed.zhaleika" ) \
KOMP_ENUM_VALUE( WIND_REED_ZURLA, "wind.reed.zurla" ) \
KOMP_ENUM_VALUE( WIND_REED_ZURNA, "wind.reed.zurna" ) \
KOMP_ENUM_VALUE( WOOD_AGOGO_BLOCK, "wood.agogo-block" ) \
KOMP_ENUM_VALUE( WOOD_AGUNG_A_TAMLANG, "wood.agung-a-tamlang" ) \
KOMP_ENUM_VALUE( WOOD_AHOKO, "wood.ahoko" ) \
KOMP_ENUM_VALUE( WOOD_BONES, "wood.bones" ) \
KOMP_ENUM_VALUE( WOOD_CASTANETS, "wood.castanets" ) \
KOMP_ENUM_VALUE( WOOD_CLAVES, "wood.claves" ) \
KOMP_ENUM_VALUE( WOOD_DRUM_STICKS, "wood.drum-sticks" ) \
KOMP_ENUM_VALUE( WOOD_GOURD, "wood.gourd" ) \
KOMP_ENUM_VALUE( WOOD_GRANITE_BLOCK, "wood.granite-block" ) \
KOMP_ENUM_VALUE( WOOD_GUBAN, "wood.guban" ) \
KOMP_ENUM_VALUE( WOOD_GUIRO, "wood.guiro" ) \
KOMP_ENUM_VALUE( WOOD_HYOUSHIGI, "wood.hyoushigi" ) \
KOMP_ENUM_VALUE( WOOD_IPU, "wood.ipu" ) \
KOMP_ENUM_VALUE( WOOD_JAM_BLOCK, "wood.jam-block" ) \
KOMP_ENUM_VALUE( WOOD_KAEKEEKE, "wood.kaekeeke" ) \
KOMP_ENUM_VALUE( WOOD_KAGUL, "wood.kagul" ) \
KOMP_ENUM_VALUE( WOOD_KALAAU, "wood.kalaau" ) \
KOMP_ENUM_VALUE( WOOD_KASHIKLAR, "wood.kashiklar" ) \
KOMP_ENUM_VALUE( WOOD_KUBING, "wood.kubing" ) \
KOMP_ENUM_VALUE( WOOD_PAN_CLAPPERS, "wood.pan-clappers" ) \
KOMP_ENUM_VALUE( WOOD_SAND_BLOCK, "wood.sand-block" ) \
KOMP_ENUM_VALUE( WOOD_SLAPSTICK, "wood.slapstick" ) \
KOMP_ENUM_VALUE( WOOD_STIR_DRUM, "wood.stir-drum" ) \
KOMP_ENUM_VALUE( WOOD_TEMPLE_BLOCK, "wood.temple-block" ) \
KOMP_ENUM_VALUE( WOOD_TIC_TOC_BLOCK, "wood.tic-toc-block" ) \
KOMP_ENUM_VALUE( WOOD_TONETANG, "wood.tonetang" ) \
KOMP_ENUM_VALUE( WOOD_WOOD_BLOCK, "wood.wood-block" ) \


#include "kern/EnumWithString.def"
}

// Semitone Inc. Confidential Information.
// TM and (c) 2016-present Semitone Inc.  All Rights Reserved.
// Reproduction in whole or in part without prior written permission of a
// duly authorized representative is prohibited.
